### ISSUE TITLE
Check for remove-overlap bugs

### ISSUE THREAD

**Issue by davelab6** [enathu/neythal-font#6]
<img width="867" alt="screen shot 2016-06-02 at 12 42 24" src="https://cloud.githubusercontent.com/assets/261579/15756678/7ff0ac2c-28bf-11e6-9f82-ecbddb032047.png">

Remove overlap bugs :)

**Comment by enathu** [comment]
Fixed. :)

**Comment by davelab6** [comment]
Thank you!! :) Did you find any other glyphs with problems?

**Comment by enathu** [comment]
I found a similar issue (wrong direction overlap) with lowercase o with stroke (**ø**) and fixed it. :)
